### ISSUE TITLE
Villagers not saving their trades 1.14.4

### ISSUE THREAD

**Issue by Reynard-G** [MarioFinale/VillagerSaver#1]
When I tested this in my 1.14.4 Paperspigot (latest) server, the villager would have a specific trade that it would deduct the price from after being healed. Instead after the zombie villager was cured, it would reset its trades and turn into a villages with no profession.

**Comment by Zackyy1** [comment]
Is this going to be updated to 1.15.2+ and fixed?

**Comment by MarioFinale** [comment]
[Updated to 1.16.3 and fixed](https://github.com/MarioFinale/VillagerSaver/releases/tag/0.1.2)
