### ISSUE TITLE
(Spigot) Villager Reputations not staying through rezombification/curing

### ISSUE THREAD

**Issue by JarheadHME** [MarioFinale/VillagerSaver#13]
Now, on a spigot server I play on with some friends, not only do they not stack, only the most recent cure has any effect at all. So if I cure the villager, I get the discount, but I cannot increase the discount by re-curing them, and if someone else cures them, my discount vanishes. We currently have the Jan 23 1.1.5 version of the plugin.

When i was talking to the server owner about it, I saw this in the error:

`Caused by: java.lang.NoSuchMethodError: 'java.util.Map net.minecraft.server.v1_16_R3.Reputation.getReputations()'`

**Comment by MarioFinale** [comment]
Hi @JarheadHME
Which release of spigot is the server owner using?

**Comment by JarheadHME** [comment]
I don't actually know offhand, but I was trying it on a local spigot server which was on the latest release from buildtools, and was having the same error.

Worth mentioning @Kasama has the error fixed in their fork [here](https://github.com/Kasama/VillagerSaver)

**Comment by MarioFinale** [comment]
Hi, just merged Kasama's fork into the main repo. His method is better. Just tested it and It works flawlessly.
