### ISSUE TITLE
Error loading blacklist

### ISSUE THREAD

**Issue by PhoenixIV** [MarioFinale/VillagerSaver#15]
This is a cosmetic issue: On first start the plugin throws an error, because the blacklist does not exist (yet). Maybe this should not show as error?

I also noticed that you use the INFO type output for the error message. FYI there is also an error output line, that can be used by admins to e.g. write into a log file or use red color: https://stackoverflow.com/questions/3163399/difference-between-system-out-println-and-system-err-println

Unrelated: This plugin seems to work fine with craftbukkit. Maybe you therefore want to list it on https://dev.bukkit.org/ ?

**Comment by MarioFinale** [comment]
Thank for the insight, since those aren't critical flaws they aren't too high on my list of priorities but I'll try to fix them as soon as possible.

**Comment by MarioFinale** [comment]
Hi, I fixed the issues but I'm waiting for Spigot's staff to unban my account. 
For some reason they banned it for uploading a malicious plugin (????) even though this plugin is Open Source.

**Comment by MarioFinale** [comment]
Fixed on 1.2.3

**Comment by PhoenixIV** [comment]
😊

I know it is only minor, but I like to smooth those edges for my own stuff, too, so good to hear you picked up on this!
