### ISSUE TITLE
[Feature request] Config file for Blacklist

### ISSUE THREAD

**Issue by sphings79** [MarioFinale/VillagerSaver#2]
Hi,

really great plugin,
would be great to have a config file, for adding forbidden Worlds.
So that i can control to not function on the plot world.

regards

sphings

**Comment by MarioFinale** [comment]
@sphings79 Thanks for the feedback! 
Added in [1.1.1](https://github.com/MarioFinale/VillagerSaver/releases/tag/1.1.1)
