### ISSUE TITLE
Cured villagers cannot work until their old workstation is destroyed

### ISSUE THREAD

**Issue by joshqwang** [MarioFinale/VillagerSaver#6]
Whenever a villager is cured, they will never resupply their trades. It can be fixed in game by destroying their workstation and replacing it.

**Comment by MarioFinale** [comment]
@joshqwang Thanks for the feedback!
Should have been fixed on [1.1.2](https://github.com/MarioFinale/VillagerSaver/releases/tag/1.1.2).
