### ISSUE TITLE
Discount going away for cured zombie villager

### ISSUE THREAD

**Issue by dollusion** [MarioFinale/VillagerSaver#9]
I cured a zombie villager to get better trades on easy difficulty but after some time he lost his discount. I turned him into a zombie and cured him again, which only resulted in the price going up.

**Comment by MarioFinale** [comment]
Hi, do you have any repro steps for your problem?
I haven't been able to reproduce that behavior on my test servers (spigot 1.16.5 and papermc 1.16.5)
